### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by kts707** [tytrusty/mfem#3]
Hi,

Thanks for the great work! 

I was trying to build on a Ubuntu 24.04 machine, but when I run `make -j4`, I get the following error. How do I fix it? Thanks a lot!

```
[  1%] Built target stb
[  1%] Built target glad
[  9%] Built target spdlog
[ 11%] Built target glfw
[ 12%] Built target finitediff_finitediff
[ 15%] Built target imgui
[ 46%] Built target polyscope
[ 46%] Linking CXX shared library lib/libmixed_fem_lib.so
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/config.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/config.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/energies/arap.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/energies/arap.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/energies/corotational.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/energies/corotational.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/energies/fixed_corotational.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/energies/fixed_corotational.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/energies/fung.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/energies/fung.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/energies/material_model.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/energies/material_model.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/energies/neohookean.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/energies/neohookean.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/energies/stable_neohookean.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/energies/stable_neohookean.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/factories/boundary_condition_factory.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/factories/boundary_condition_factory.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/factories/integrator_factory.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/factories/integrator_factory.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/factories/linear_solver_factory.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/factories/linear_solver_factory.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/factories/material_model_factory.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/factories/material_model_factory.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/factories/optimizer_factory.cpp.o:(.bss+0x1): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/factories/optimizer_factory.cpp.o:(.bss+0x2): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/factories/variable_factory.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/factories/variable_factory.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/mesh/mesh.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/mesh/mesh.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/mesh/meshes.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/mesh/meshes.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/mesh/tet_mesh.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/mesh/tet_mesh.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/mesh/tri2d_mesh.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/mesh/tri2d_mesh.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/optimizers/newton_optimizer.cpp.o:(.bss+0x0): multiple definition of `mfem::default_optimizer_callback'; CMakeFiles/mixed_fem_lib.dir/src/factories/optimizer_factory.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/optimizers/newton_optimizer.cpp.o:(.bss+0x1): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/optimizers/newton_optimizer.cpp.o:(.bss+0x2): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/optimizers/optimizer.cpp.o:(.bss+0x0): multiple definition of `mfem::default_optimizer_callback'; CMakeFiles/mixed_fem_lib.dir/src/factories/optimizer_factory.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/optimizers/optimizer.cpp.o:(.bss+0x1): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/optimizers/optimizer.cpp.o:(.bss+0x2): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/optimizers/optimizer_data.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/optimizers/optimizer_data.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/simulation_state.cpp.o:(.bss+0x0): multiple definition of `mfem::default_optimizer_callback'; CMakeFiles/mixed_fem_lib.dir/src/factories/optimizer_factory.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/simulation_state.cpp.o:(.bss+0x1): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/simulation_state.cpp.o:(.bss+0x2): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/svd/dsvd.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/svd/dsvd.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/time_integrators/BDF.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/time_integrators/BDF.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/utils/pinning_matrix.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/utils/pinning_matrix.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/utils/sparse_utils.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/utils/sparse_utils.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/variables/displacement.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/variables/displacement.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/variables/mixed_stretch.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/variables/mixed_stretch.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/variables/stretch.cpp.o:(.bss+0x0): multiple definition of `default_linesearch_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/mixed_fem_lib.dir/src/variables/stretch.cpp.o:(.bss+0x1): multiple definition of `default_callback'; CMakeFiles/mixed_fem_lib.dir/src/boundary_conditions/boundary_condition.cpp.o:(.bss+0x1): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/mixed_fem_lib.dir/build.make:607: lib/libmixed_fem_lib.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:295: CMakeFiles/mixed_fem_lib.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```
